name: First CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: ["win-x64", "linux-x64"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore

      - name: Publish for ${{ matrix.rid }}
        run: dotnet publish -o build_output -r ${{ matrix.rid }} /p:PublishSingleFile=true /p:AssemblyName=app --self-contained

      - name: Archive files
        run: tar -cvf app-${{ matrix.rid }}.tar build_output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.rid }}
          path: app-${{ matrix.rid }}.tar
